### ISSUE TITLE
Link notice

### ISSUE THREAD

**Issue by Elise39u** [justinvandelaar/InteractiveList#4]
Apprently in the product owners Excel copying a link into the a cell results it bening label as:
`Hyperlink text` -> Which holds the link

Its a small issues that requires some thought. Since the json converter takes apprently what stands in the cell
Resulting in a link that is printed out but not working

**Comment by justinvandelaar** [comment]
The situation has a fix now or a temp fix. This temp has has also been added to the followers guide. Under section 1.3
